    server {
        listen 80;

        location /api/notifications/stream { 
                proxy_pass http://localhost:4000/;  # 백엔드 포트: 구체적인 거 먼저
                proxy_http_version 1.1;
                proxy_set_header Connection '';
                proxy_set_header Host $host;
                proxy_buffering off;
                proxy_read_timeout 3600s;
                proxy_send_timeout 3600s;
        }

        location /api/ {
                proxy_pass http://localhost:4000; # 백엔드 일반식
        }

        location /images/ {
                proxy_pass http://localhost:4000; # 백엔드 static (불필요할 수 있음)
        }

        location / {
                proxy_pass http://localhost:3000; # 프론트엔드 일반식
                proxy_set_header Host $host;

        }
    }
