@baseUrl = http://localhost:3000

### 공개: 아파트 목록 조회
### query keyword: name, address, description
### query filters: name, address
GET {{baseUrl}}/apartments/public
###
GET {{baseUrl}}/apartments/public?address=길목

### 공개: 아파트 상세 조회
GET {{baseUrl}}/apartments/public/fa1331b1-ca0c-4a8f-be39-9ef346bda066

### 슈퍼관리자/관리자: 아파트 목록 조회
### pagination: page, limit
### query filters: name, address
### query exactFilters: apartmentStatus
### query keyword: name, address, (관계형) admin name, admin email
GET {{baseUrl}}/apartments?keyword=보고싶은

### 슈퍼관리자/관리자: 아파트 상세 조회
GET {{baseUrl}}/apartments/fa1331b1-ca0c-4a8f-be39-9ef346bda066
