@baseUrl = http://localhost:3000

### 댓글 생성
POST {{baseUrl}}/comments
Content-Type: application/json

{
  "content": "와~ 너무 기대됩니다.",
  "boardType": "NOTICE",
  "boardId": "5ca5fce9-deed-4e00-b35d-f8a3c7c679e8"
}

### 댓글 수정
PATCH {{baseUrl}}/comments/74eaecea-9945-4988-ab3a-a451d8e694cf
Content-Type: application/json

{
  "content": "맞아요. 너무 지저분해요.",
  "boardType": "COMPLAINT",
  "boardId": "ae7c9a75-5191-41cc-95fa-b7ed9a07aba7"
}

### 댓글 삭제
DELETE {{baseUrl}}/comments/74eaecea-9945-4988-ab3a-a451d8e694cf