@baseUrl = http://localhost:3000

### 댓글 생성
POST {{baseUrl}}/comments
Content-Type: application/json

{
  "content": "[관리자] 청소하시는 아줌마께 주기적인 청소 부탁드렸고, 전체 공지도 올렸습니다. 시정되지 않으면 다시 민원접수 부탁드립니다.",
  "boardType": "COMPLAINT",
  "boardId": "b02d3c2a-deac-49bc-8adb-4c9bce336a9f"
}

### 댓글 수정
PATCH {{baseUrl}}/comments/0a992a79-9e54-4df3-9ce3-777f188d42c9
Content-Type: application/json

{
  "content": "맞아요. 너무 지저분해요.",
  "boardType": "COMPLAINT",
  "boardId": "b02d3c2a-deac-49bc-8adb-4c9bce336a9f"
}

### 댓글 삭제
DELETE {{baseUrl}}/comments/10f13d95-d875-453b-bce0-0ee4adc4222b