@baseUrl = http://localhost:4000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNzBhNWNmLTA3ZmMtNDE3ZC04NmEwLTU0NzcyMmRiYWJkMSIsImlhdCI6MTc3NDg0NzYzMiwiZXhwIjoxNzc0ODUxMjMyfQ.jIVww7ld4tMRvOKAOhqE544HYxdMetoLXrL1tqb8qTs

### 민원 등록 // boardId는 생략. apartmentId 통해 가져옴
POST {{baseUrl}}/complaints
Cookie: access-token={{accessToken}}
Content-Type: application/json

{
  "title": "201동 앞 인도와 도로 사이의 배수로 막힘",
  "content": "내려온 흙으로 막혔나봐요. 비가 오면 물이 넘쳐 흘려요.",
  "isPublic": true,
  "boardId": "b7d46d6a-0926-4f6f-8802-a06aaaae2557",
  "status": "PENDING"
}

### 전체 민원 조회
GET {{baseUrl}}/complaints
Cookie: access-token={{accessToken}}


### 전체 민원 조회: 검색
### status, isPublic, dong, ho, 
### keyword(title, content)
GET {{baseUrl}}/complaints?isPublic=false

### 민원 상세 조회
GET {{baseUrl}}/complaints/6ef988d3-b623-4da2-b29c-4f9b0534be80
Cookie: access-token={{accessToken}}
### 사용자: 민원 수정
PATCH {{baseUrl}}/complaints/ae7c9a75-5191-41cc-95fa-b7ed9a07aba7
Content-Type: application/json

{
  "title": "101동 화단 근처 흡연",
  "content": "근처에 놀이터가 있어 아이들 간접 흡연이 염려됩니다.",
  "isPublic": false
}

### 민원 삭제
DELETE {{baseUrl}}/complaints/ae7c9a75-5191-41cc-95fa-b7ed9a07aba7

### 슈퍼관리자, 관리자: 민원상태 변경
PATCH {{baseUrl}}/complaints/ae7c9a75-5191-41cc-95fa-b7ed9a07aba7/status
Content-Type: application/json

{
  "status": "RESOLVED"
}

