@baseUrl = http://localhost:3001
@accessToken_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZkNGNjNzMxLThmNzEtNGI4Ni1hZTg1LWY1M2FlNGUzMWY0NyIsImlhdCI6MTc3NDk4ODI4OSwiZXhwIjoxNzc0OTkxODg5fQ.jpqy7e07iAeXP8HzK0hmy7k5dehpi_4vzl31iQZGtRo

@accessToken_user2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhMDQ4MDMwLTQ1OGEtNDc1MC05MGU4LTY5MGQwMTEyZmI5NiIsImlhdCI6MTc3NDk4ODM2NywiZXhwIjoxNzc0OTkxOTY3fQ.2sGwqY8IP4KCkGg4nCYn74ab-Cds4naoesVR-zIXnKk

@accessToken_user1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1ZGRiNWFmLWM0OGEtNDQ2Ny05ZWRhLWUxMzg5NjcyMWZiMiIsImlhdCI6MTc3NDk4ODQyOSwiZXhwIjoxNzc0OTkyMDI5fQ.4xfxeLBgfLk5dzqwHOvslAYl94lqijD7BUncaRYyDg4

###
GET {{baseUrl}}/users/me/myInfo
Cookie: access-token={{accessToken_user1}}

### 민원 등록 // boardId는 생략. apartmentId 통해 가져옴
POST {{baseUrl}}/complaints
Cookie: access-token={{accessToken_user1}}
Content-Type: application/json

{
  "title": "101동 앞 인도와 도로 사이의 배수로 막힘",
  "content": "내려온 흙으로 막혔나봐요. 비가 오면 물이 넘쳐 흘려요.",
  "isPublic": true,
  "boardId": "31b39930-0759-4a94-bdd2-049802cdaa5f",
  "status": "PENDING"
}

### 전체 민원 조회
GET {{baseUrl}}/complaints
Cookie: access-token={{accessToken_user1}}


### 전체 민원 조회: 검색
### status, isPublic, dong, ho, 
### keyword(title, content)
GET {{baseUrl}}/complaints?isPublic=true
Cookie: access-token={{accessToken_user1}}

### 민원 상세 조회
GET {{baseUrl}}/complaints/1276895c-11ce-4913-bb4c-0ee5de4c2a92
Cookie: access-token={{accessToken_admin}}
### 사용자: 민원 수정
PATCH {{baseUrl}}/complaints/ae7c9a75-5191-41cc-95fa-b7ed9a07aba7
Cookie: access-token={{accessToken_user1}}
Content-Type: application/json

{
  "title": "101동 화단 근처 흡연",
  "content": "근처에 놀이터가 있어 아이들 간접 흡연이 염려됩니다.",
  "isPublic": false
}

### 민원 삭제
DELETE {{baseUrl}}/complaints/ae7c9a75-5191-41cc-95fa-b7ed9a07aba7
Cookie: access-token={{accessToken_admin}}

### 슈퍼관리자, 관리자: 민원상태 변경
PATCH {{baseUrl}}/complaints/1276895c-11ce-4913-bb4c-0ee5de4c2a92/status
Cookie: access-token={{accessToken_admin}}
Content-Type: application/json

{
  "status": "RESOLVED"
}

