@baseUrl = http://localhost:3000

### 민원 등록 // boardId는 생략. apartmentId 통해 가져옴
POST {{baseUrl}}/complaints
Content-Type: application/json

{
  "title": "101동 화단 근처 끽연",
  "content": "근처에 놀이터가 있어 아이들 2차 흡연이 염려됩니다. 담배꽁초도 제대로 치우세요.",
  "isPublic": true,
  "status": "PENDING"
}

### 전체 민원 조회
GET {{baseUrl}}/complaints
### 전체 민원 조회: 검색 by status, isPublic, dong, ho, keyword(title, content)
GET {{baseUrl}}/complaints?status=PENDING&keyword=한밤중

### 민원 상세 조회
GET {{baseUrl}}/complaints/b02d3c2a-deac-49bc-8adb-4c9bce336a9f

### 사용자: 민원 수정
PATCH {{baseUrl}}/complaints/b02d3c2a-deac-49bc-8adb-4c9bce336a9f
Content-Type: application/json

{
  "title": "101동 화단 근처 끽연",
  "content": "근처에 놀이터가 있어 아이들 2차 흡연이 염려됩니다.",
  "isPublic": true
}

### 민원 삭제
DELETE {{baseUrl}}/complaints/5d335528-769b-45cd-891e-b7d69b891f98

### 슈퍼관리자, 관리자: 민원 수정
PATCH {{baseUrl}}/complaints/ee9cc55a-970d-472e-9763-e518250910b9/status
Content-Type: application/json

{
  "status": "RESOLVED"
}

