@baseUrl = http://localhost:4000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNzBhNWNmLTA3ZmMtNDE3ZC04NmEwLTU0NzcyMmRiYWJkMSIsImlhdCI6MTc3NDg0NDkxNSwiZXhwIjoxNzc0ODQ4NTE1fQ.X0oa7oz58jvcp-YQIB9Hu_9NRi6oG7MjYsRyBXuFu-Y


### 이벤트 목록 조회
### apartmentId, year, month
GET {{baseUrl}}/event?apartmentId=ff632b77-6efa-4bad-b8cf-41c6853b91ed&year=2026&month=3
Cookie: access-token={{accessToken}}


### 이벤트 생성 또는 업데이트
PUT {{baseUrl}}/event
Content-Type: application/json

{
  "boardType": "NOTICE",
  "boardId": "8d8f29d1-60aa-45dd-a2b3-a5a7637d1729",
  "startDate": "2026-03-23 18:45:00",
  "endDate": "2026-03-23 18:55:00"
}

### 이벤트 삭제
DELETE {{baseUrl}}/event/1dba8d7e-f78b-4b00-b44f-291e8344bbdc
