@baseUrl = http://13.125.213.35
@accessToken_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YjE2MjU5LTViOTctNGZmNC04NjdkLTM4YjQzYzcyZTg1OCIsImlhdCI6MTc3NDg2NjE1MCwiZXhwIjoxNzc0ODY5NzUwfQ.Ej1pAc2H1NEU5blAfXo_yRme2VHewL8pY0k_wZNyNRc


### 이벤트 목록 조회
### apartmentId, year, month
GET {{baseUrl}}/event?apartmentId=83661321-7be3-4df1-8b32-a596e95eb292&year=2026&month=3
Cookie: access-token={{accessToken_admin}}


### 이벤트 생성 또는 업데이트
PUT {{baseUrl}}/event
Content-Type: application/json

{
  "boardType": "NOTICE",
  "boardId": "8d8f29d1-60aa-45dd-a2b3-a5a7637d1729",
  "startDate": "2026-03-23 18:45:00",
  "endDate": "2026-03-23 18:55:00"
}

### 이벤트 삭제
DELETE {{baseUrl}}/event/1dba8d7e-f78b-4b00-b44f-291e8344bbdc
Cookie: access-token={{accessToken_admin}}
