@baseUrl = http://localhost:4000

### 이벤트 목록 조회
### apartmentId, year, month
GET {{baseUrl}}/event?apartmentId=188fdedf-2659-4491-b740-8a35f969d7b4&year=2026&month=3


### 이벤트 생성 또는 업데이트
PUT {{baseUrl}}/event
Content-Type: application/json

{
  "boardType": "NOTICE",
  "boardId": "8d8f29d1-60aa-45dd-a2b3-a5a7637d1729",
  "startDate": "2026-03-23 18:45:00",
  "endDate": "2026-03-23 18:55:00"
}

### 이벤트 삭제
DELETE {{baseUrl}}/event/1dba8d7e-f78b-4b00-b44f-291e8344bbdc
