@baseUrl = http://localhost:3000

### SSE
GET {{baseUrl}}/notifications/SSE

### 알림 읽음 처리
PATCH {{baseUrl}}/notifications/6d53703d-4689-4bea-b031-35f0f7a246a7/read


#################################### 부가 기능

### 알림 목록 조회: all
GET {{baseUrl}}/notifications
### 알림 목록 조회: unread
GET {{baseUrl}}/notifications/unread

### 알림 읽음 일괄 처리
PATCH {{baseUrl}}/notifications/read

### 알림 보내기
POST {{baseUrl}}/notifications/send
Content-Type: application/json

{ 
  "receiverId": "bf4440e6-4f29-4cc3-a23f-25dd830c4cf1",
  "notiType": "NOTICE",
  "targetId": "9ebc9d3d-2b2e-4e77-937a-9a2b877cfd1b",
  "content": "[알림] 테스트"
}

