@baseUrl = http://localhost:4000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNzBhNWNmLTA3ZmMtNDE3ZC04NmEwLTU0NzcyMmRiYWJkMSIsImlhdCI6MTc3NDg0NDkxNSwiZXhwIjoxNzc0ODQ4NTE1fQ.X0oa7oz58jvcp-YQIB9Hu_9NRi6oG7MjYsRyBXuFu-Y


### 공지사항 등록
POST {{baseUrl}}/notices
Cookie: access-token={{accessToken}}
Content-Type: application/json

{
  "category": "RESIDENT_COUNCIL",
  "title": "반상회 개최일 변경 안내",
  "content": "마지막 주 목요일에서 첫째 주 목요일로 변경되었습니다.",
  "boardId": "3c5522a9-c0d5-4748-b0c9-c11245b6ba82",
  "isPinned": true
}

  # "startDate": "2026-03-31 13:00:00",
  # "endDate": "2026-03-31 17:00:00"

### 공지사항 전체 조회
### page, limit(11)
### category
### keyword: title, content
GET {{baseUrl}}/notices
Cookie: access-token={{accessToken}}
###
GET {{baseUrl}}/notices?category=RESIDENT_VOTE
Cookie: access-token={{accessToken}}

### 공지사항 상세 조회
GET {{baseUrl}}/notices/4c26fdfe-a077-4986-85b2-8666e2bb33c2
Cookie: access-token={{accessToken}}

### 공지사항 수정
PATCH {{baseUrl}}/notices/4c26fdfe-a077-4986-85b2-8666e2bb33c2
Cookie: access-token={{accessToken}}
Content-Type: application/json

{
  "boardId": "3c5522a9-c0d5-4748-b0c9-c11245b6ba82",
  "title": "[공지] 불우이웃 돕기 바자회 개최 (관리동 앞)",
  "isPinned": false
}

  # "category": "RESIDENT_VOTE",
  # "title": "[공지] 투표종료 (101동 앞 화단 꽃 종류 선정)",
  # "content": "화단에 심을 꽃을 선택해 주세요 (공지보드 사진 참조).",
  # "startDate": "2026-03-14 21:30:00",
  # "endDate": "2026-03-14 22:00:00"

### 공지사항 삭제
DELETE {{baseUrl}}/notices/5ca5fce9-deed-4e00-b35d-f8a3c7c679e8
