@baseUrl = http://13.125.213.35
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YjE2MjU5LTViOTctNGZmNC04NjdkLTM4YjQzYzcyZTg1OCIsImlhdCI6MTc3NDg3NTM2MSwiZXhwIjoxNzc0ODc4OTYxfQ.4qMovvMFtquaaN81Z6yyXErp0zLT1GtRb8GI5eSWDoY



### stream: SSE connection by clients
GET {{baseUrl}}/notifications/stream

### 읽지 않은 알림 실시간 수신
### start a cron job every 30 sec
GET {{baseUrl}}/notifications/SSE
Cookie: access-token={{accessToken}}

### 알림 읽음 처리
PATCH {{baseUrl}}/notifications/b1313ccd-60f2-4ef9-8e25-78516024307b/read
Cookie: access-token={{accessToken}}

#################################### 부가 기능

### 알림 목록 조회: all
GET {{baseUrl}}/notifications
Cookie: access-token={{accessToken}}

### 알림 목록 조회: unread
GET {{baseUrl}}/notifications/unread
Cookie: access-token={{accessToken}}

### 알림 읽음 일괄 처리
PATCH {{baseUrl}}/notifications/read
Cookie: access-token={{accessToken}}

### 알림 보내기
POST {{baseUrl}}/notifications/send
Content-Type: application/json

{ 
  "receiverId": "bf4440e6-4f29-4cc3-a23f-25dd830c4cf1",
  "notiType": "NOTICE",
  "targetId": "9ebc9d3d-2b2e-4e77-937a-9a2b877cfd1b",
  "content": "[알림] 테스트"
}

