@baseUrl = http://13.125.213.35

@accessToken_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2YjE2MjU5LTViOTctNGZmNC04NjdkLTM4YjQzYzcyZTg1OCIsImlhdCI6MTc3NDg3NTM2MSwiZXhwIjoxNzc0ODc4OTYxfQ.4qMovvMFtquaaN81Z6yyXErp0zLT1GtRb8GI5eSWDoY

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwMWNkNTNjLWVlYmItNGVmOC05NmRlLTliZTNhODRlMzhlYSIsImlhdCI6MTc3NDg2MzkwNiwiZXhwIjoxNzc0ODY3NTA2fQ.iTHg_mP5fw0w6CKWk66-DCyxgtV9y_WscJFND-1Vhio



GET {{baseUrl}}/poll-scheduler/ping
Cookie: access-token={{accessToken_admin}}

### 투표 글 작성
POST {{baseUrl}}/polls
Cookie: access-token={{accessToken}}
Content-Type: application/json

{
  "boardId": "d70dddd4-7208-48aa-bb16-86efc15384c5",
  "status": "IN_PROGRESS",
  "title": "청소 용역업체 계약 연장 어부",
  "content": "2026년도에도 같은 청소 용역업체를 이용할지 찬반 투표 실시합니다.",
  "buildingPermission": 0,
  "startDate": "2026-03-30 18:40:00",
  "endDate": "2026-03-30 18:45:00",
  "options": [
    { "title": "찬성" },
    { "title": "반대" }
  ]
}

### 투표 글 전체 조회
### page(1), limit(11)
### buildingPermission
### status
### keyword: title, content
GET {{baseUrl}}/polls
Cookie: access-token={{accessToken_admin}}

### 투표 글 상세 조회
GET {{baseUrl}}/polls/45bd6594-65b0-477e-91b2-e687d464941b
Cookie: access-token={{accessToken_admin}}

### 투표 글 수정
PATCH {{baseUrl}}/polls/f36fbd24-e6e4-4da8-8600-ec841b2c691f
Cookie: access-token={{accessToken_admin}}
Content-Type: application/json

{
  "buildingPermission": 0,
  "startDate": "2026-03-24 18:45:00",
  "endDate": "2026-03-24 18:55:00"
}

# {
#   "title": "플리마켓 개최일 선정",
#   "content": "5월 플리마켓 날짜 투표입니다.",
#   "buildingPermission": 0,
#   "startDate": "2026-03-23 17:47:00",
#   "endDate": "2026-03-23 18:00:00",
#   "status": "IN_PROGRESS",
#   "options": [
#     { "title": "5일 수요일" },
#     { "title": "9일 토요일" },
#     { "title": "16일 토요일" }
#   ]
# }

### 투표 글 삭제
DELETE {{baseUrl}}/polls/e2bf6f53-0f8a-413f-b6c1-7ce12e990fe7
Cookie: access-token={{accessToken_admin}}


### 투표하기
POST {{baseUrl}}/options/209f43d8-2bab-46c7-86fa-c1b2b4dac8d9/vote
Cookie: access-token={{accessToken}}
###
POST {{baseUrl}}/options/486e60e9-e4cb-442b-9215-0761dc578486/vote
Cookie: access-token={{accessToken}}


### 투표 취소
DELETE {{baseUrl}}/options/486e60e9-e4cb-442b-9215-0761dc578486/vote
Cookie: access-token={{accessToken}}






