@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/residents/
###
POST {{baseUrl}}/residents/
###
POST {{baseUrl}}/residents/from-users/abcd
###
GET {{baseUrl}}/residents/file/template
###
POST {{baseUrl}}/residents/from-file
###
GET {{baseUrl}}/residents/file
###
GET {{baseUrl}}/residents/abcd
###
PATCH {{baseUrl}}/residents/abcd
###
DELETE {{baseUrl}}/residents/abcd
