@baseUrl = http://localhost:3000

# 모두 관리자 권한
### 
GET {{baseUrl}}/residents?residenceStatus=RESIDENCE
###
POST {{baseUrl}}/residents
Content-Type: application/json

{
  "building": "102",
  "unitNumber": "301",
  "contact": "010-2320-6192",
  "name": "홍길동",
  "isHouseholder": "HOUSEHOLDER"
}

### 계정 생성 시에는 언제나 resident도 생기고 있기 때문에...
### 이런 경우가 어떻게 있을 수 있는지?
### apartmentDong, apartmentHo가 user에 없어서 문제 생김
# POST {{baseUrl}}/residents/from-users/abcdefg
# Content-Type: application/json

# {
#   "userId": "abcdefg"
# }

###
GET {{baseUrl}}/residents/file/template
Accept: text/csv

### 파일로부터 입주민들 생성
POST {{baseUrl}}/residents/from-file
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="file"; filename="residents.csv"
Content-Type: text/csv

< ../files/residents.csv
------MyBoundary--

### 입주민 목록 다운로드
GET {{baseUrl}}/residents/file?limit=10
###
GET {{baseUrl}}/residents/file?isRegistered=false

### 입주민 상세 조회
GET {{baseUrl}}/residents/242e30d0-eca5-4b28-87ab-e549a90e4f89
###

PATCH {{baseUrl}}/residents/e45783a5-33c4-45a5-9b7c-be01d9200332
Content-Type: application/json

{
  "building": "202",
  "unitNumber": "101",
  "contact": "010-9498-9526",
  "name": "정수영",
  "isHouseholder": "HOUSEHOLDER"
}

###
DELETE {{baseUrl}}/residents/e45783a5-33c4-45a5-9b7c-be01d9200332
