@baseUrl = http://localhost:3000

# 추가 기능
### 개발자용 무인증 기능: 사용자 목록 조회
GET {{baseUrl}}/users/getList?sort=desc


### 사용자 상세 조회
GET {{baseUrl}}/users/0f94fae1-f306-4680-b258-4658ad1c0988
### 내 정보 조회
GET {{baseUrl}}/users/me/myInfo



###
PATCH {{baseUrl}}/users/me/avatar
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="Hillie.png"
Content-Type: image/png

< ./images/users/Hillie.png
--MyBoundary--

###
PATCH {{baseUrl}}/users/me/password
Content-Type: application/json

{
  "currentPassword": "password1!",
  "newPassword": "password0!"
}