@baseUrl = http://13.125.213.35
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE1ODZiOThjLTVhN2UtNDBmNS1hZDE1LTY1MDgzMDFmNzMzZiIsImlhdCI6MTc3NDk0NTAxNywiZXhwIjoxNzc0OTQ4NjE3fQ.5qdab7nUB2F-1gVVjJJFchYUzC-jDGV-7Da7RCXVdSc

# 추가 기능
### 개발용 기능: 사용자 목록 조회
GET {{baseUrl}}/users/getList?sort=desc
### 개발용 기능: 사용자 상세 조회
GET {{baseUrl}}/users/cc70a5cf-07fc-417d-86a0-547722dbabd1



### 내 정보 조회
GET {{baseUrl}}/users/me/myInfo
Cookie: access-token={{accessToken}}


###
PATCH {{baseUrl}}/users/me/avatar
Cookie: access-token={{accessToken}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="Marlon.png"
Content-Type: image/png

< ./images/users/Marlon.png
--MyBoundary--

###
PATCH {{baseUrl}}/users/me/password
Cookie: access-token={{accessToken}}
Content-Type: application/json

{
  "currentPassword": "password0!",
  "newPassword": "password1!"
}